name: Deploy vorosvar-taxi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # we need to fetch all branches and commits so that `npm version` can find the latest tag
          fetch-depth: 0

      - name: Bump version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch -m "chore(release): Bump version to %s [skip ci]"
          git push --follow-tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project github-50dc6 --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_50DC6 }}"
